name       : haskell-terminal-size
version    : 0.3.2.1
release    : 1
source     :
    - https://hackage.haskell.org/package/terminal-size-0.3.2.1/terminal-size-0.3.2.1.tar.gz : b5c23e964756bc13914649a67d63233f59ad0a813abe7cadeb2fc9d586dc9658
license    : BSD-3-Clause
component  : programming.haskell
summary    : Get terminal window height and width
description: |
    Get terminal window height and width
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
